### ISSUE TITLE
Unassigned multi-valued attributes are set to null instead of empty array when UserResource is used.

### ISSUE THREAD

**Issue by fmemis** [pingidentity/scim2#155]
According to https://tools.ietf.org/html/rfc7644#section-3.3 multi valued attributes should be set to [] in case clients  intend to override  server-defaulted values. 

However when public <T extends com.unboundid.scim2.common.ScimResource> T create(String endpoint,T resource) is called with resource of type UserResource, ALL unassigned values are set to null. This is ok for single valued attributes but problematic for multi-valued ones and may result to com.unboundid.scim2.common.exceptions.BadRequestException.

{"schemas" : [ "urn:ietf:params:scim:api:messages:2.0:Error" ],
  "status" : "400",
  "scimType" : "invalidSyntax",
  "detail" : "Request is unparsable, syntactically incorrect, or violates schema."}

Example of request body that is being sent to the service provider:
{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "id": null,
  "externalId": null,
  "meta": null,
  "userName": "jsmith",
  "name": {
    "formatted": null,
    "familyName": null,
    "givenName": null,
    "middleName": null,
    "honorificPrefix": null,
    "honorificSuffix": null
  },
  "displayName": null,
  "nickName": null,
  "profileUrl": null,
  "title": null,
  "userType": null,
  "preferredLanguage": null,
  "locale": null,
  "timezone": null,
  "active": true,
  "password": "secret",
  "emails": [
    {
      "value": "jsmith@examplemail.com",
      "display": null,
      "type": null,
      "primary": true
    },
    {
      "value": "jsmithSecondMail@examplemail.gr",
      "display": null,
      "type": null,
      "primary": null
    }
  ],
  "phoneNumbers": [
    {
      "value": "+449878979789",
      "display": null,
      "type": null,
      "primary": true
    }
  ],
  "ims": null,
  "photos": null,
  "addresses": null,
  "groups": null,
  "entitlements": null,
  "roles": null,
  "x509Certificates": null
}

As mentioned before, the multi-valued attributes of the above request are expected to be set to []. For example: 

{
  "schemas": [
    "urn:ietf:params:scim:schemas:core:2.0:User"
  ],
  "id": null,
  "externalId": null,
  "meta": null,
  "userName": "jsmith",
     ...
     ...
  "phoneNumbers": [
    {
      "value": "+449878979789",
      "display": null,
      "type": null,
      "primary": true
    }
  ],
  "ims": [],
  "photos": [],
  "addresses": [],
  "groups": [],
  "entitlements": [],
  "roles": [],
  "x509Certificates": []
}

**Comment by kqarryzada** [comment]
The SDK sets multi-valued fields to null so that Jackson does not include those values when the UserResource is serialized into JSON. This is the default behavior of the object mapper used by the SCIM SDK. However, it appears that you may be using an object mapper that is configured to explicitly write out null values. If so, then it's possible that your project has done something like:
```java
OBJECT_MAPPER.setSerializationInclusion(JsonInclude.Include.ALWAYS);
```

You could update this configuration to resolve this issue. If the object mapper cannot be updated, another option would be to create your own class that extends UserResource. Then, in the constructor, set multi-valued fields like `emails` to be empty lists:
```java
public class MyUser extends UserResouce {
  public MyUser() {
    super();
    setEmails(Collections.emptyList();
    // etc.
  }
}
```
Then, any instance of `MyUser` (or whatever subclass) would always start with an empty array by default. You would need to make sure that methods like `setEmails` will set the fields to empty lists if a caller passes in a `null`, too.
