### ISSUE TITLE
Add support conditional support for non compliant SCIM servers (AWS).

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [pingidentity/scim2#176]
I would like to manage AWS users and groups with the scim2 library. AWS has some [known limitations](https://docs.aws.amazon.com/singlesignon/latest/developerguide/limitations.html), and some attributes are not supported;
```
>   "email["display"]"
>   "ims"
>   "photos"
>   "groups"
>   "entitlements"
>   "x509Certificates"
```
I would like to be able to create a UserResource object, and remove some fields from the request that is sent to SCIM server.

I tried to use RemoveExtension function, but it does not remove the class.
Would it be possible, to modify a userresource to omit some values?

I can solve the issue, by creating a new custom UserResource, but it would be interesting, if this could be done, by calling some function over the default UserResource.

Thanks for your work!!

**Comment by kqarryzada** [comment]
I think the best way to handle this case would indeed be to create your own class that extends UserResource. This would allow you to specify null values for these parameters in the constructor, and override the behavior of getters and setters. For example, if you only wanted to restrict photos, you could do something like:
```java
public class AWSUser extends UserResource {
  public AWSUser() {
    super();
    setPhotos(null);
  }

  @Override
  public UserResource setPhotos(final List<Photo> photos) {
    // Throw an exception or ignore the request.
    return this;
  }
}
```

By setting these parameters to be null and unmodifiable, it would guarantee that they will not appear when this class (and thus, an AWS SCIM user) is serialized into JSON. It also makes conceptual sense, since this would create a class that follows the conventions and restraints that AWS users (or any kind of custom user) would need in your system.
